Calul de la puissance d'une matrice

In [3]:
import numpy as np
n = int(input("Valeur de n ? "))
M=np.array([[2,1,1],[0,5,1],[0,0,3]])
N=M
for i in range(1,n):
  M=np.dot(M,N)
print(M)


Valeur de n ? 2
[[ 4  7  6]
 [ 0 25  8]
 [ 0  0  9]]
