In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
import io
uploaded = files.upload()

Saving tips.csv to tips.csv


In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['tips.csv']))

In [ ]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
b**2
10 * np.sin(a)
a < 35

array([ True,  True, False, False])

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [ ]:
a.min()
a.max()

50

In [ ]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.shape

(3, 4)

In [ ]:
# Somme de chaque colonne
b.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
# Somme de chaque ligne
b.sum(axis=1)

array([ 6, 22, 38])

In [ ]:
# Minimum de chaque ligne
b.min(axis=1)

array([0, 4, 8])

In [ ]:
# Somme cumulée le long de chaque ligne
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

Fonctions universelles - sin, cos, exp... See also:
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [ ]:
B = np.arange(3)
B

array([0, 1, 2])

In [ ]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [ ]:
C = np.array([2., -1, 4.])
np.add(B, C)

array([2., 0., 6.])

In [ ]:
# le dernier chiffre indique les pas de 3
d = np.arange(2, 9, 3)
d

array([2, 5, 8])

Comment créer un tableau avec des données existantes - This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])